name: Auto Green

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "update $(date)" >> green.txt
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add green.txt
          git commit -m "daily update" || exit 0
          git push
